### ISSUE TITLE
picker options not working

### ISSUE THREAD

**Issue by sibouras** [DanielVolchek/tailiscope-nvim#3]
for example i have this mapping
```lua
map("n", "<leader>fi", function()
  require("telescope").extensions.tailiscope.all({ initial_mode = "normal" })
end)
```
i expect to be in normal mode when i open the picker.

also i tried it in the setup and it doesn't work either
```lua
tailiscope = {
  initial_mode = "normal",
}
```

**Comment by DanielVolchek** [comment]
Should be fixed! Thanks for bringing this to my attention. Let me know if it works for you

**Comment by sibouras** [comment]
with the mapping example it works, but in the setup it doesn't, also i have this mapping:
```lua
map("n", "<leader>fi", function()
  require("telescope").extensions.tailiscope.all(require("telescope.themes").get_dropdown({
    initial_mode = "normal",
    layout_strategy = "vertical",
    layout_config = { height = 0.95 },
  }))
end)
```
`initial_mode` works but the theme didn't change

if i were to do it in the setup it will look like this
```lua
tailiscope = {
  initial_mode = "normal",
  theme = "dropdown",
  layout_strategy = "vertical",
  layout_config = { height = 0.95 },
}
```
but the setup options don't work

**Comment by DanielVolchek** [comment]
Fixed the setup issue! Just passed values in the wrong order. Not sure why themes aren't working, but I'll definitely look into it.

**Comment by sibouras** [comment]
works now thanks! checkout https://github.com/smartpde/telescope-recent-files implementation, i remember they had a similar issue and they fixed it

**Comment by DanielVolchek** [comment]
> works now thanks! checkout https://github.com/smartpde/telescope-recent-files implementation, i remember they had a similar issue and they fixed it

Thanks for the resource! So it looks like after my last change themes work but break preview. It's probably got something to do with preview cutoff. I'll investigate in that repo to see if they have any solutions.
