### ISSUE TITLE
How to change default config & xdg-open

### ISSUE THREAD

**Issue by mattiasbonte** [DanielVolchek/tailiscope-nvim#4]
Hi,

I've tried your cool plugin today and stumbled upon a couple of questions.

1: How does one actually change the default config? When I call `require('tailiscope').setup({ default = "all" })` it doesn't seem to find the setup method.

2: When trying `od` in normal mode (when the Telescope picker is open) nothing happens. When trying <C-o> in insert modus I get a message, `xdg-open command not found`. I assume this is because I'm on OSX and the xdg-open command it's macOs counterpart is `open`. Is there a way of setting this on a mac?

Thanks a lot.

**Comment by DanielVolchek** [comment]
Hello Mattias, thank you for trying out my plugin!

**Comment by DanielVolchek** [comment]
Hello Mattias, thank you for trying out my plugin!

The plugin is setup through telescope, the syntax would look something like this

```
require('telescope').setup({
    extensions = {
        tailiscope = {
            -- opts
        }
    }
}
```

Thank you for pointing out the bug with open doc. Looks like my solution did not work. I will try another solution and ping you when it's updated

**Comment by DanielVolchek** [comment]
Hello again Mattias. I believe I've fixed the bug. The od keybind works on my system. Please test it and let me know if it works on yours. 

Thank you!
